morai_sensor_receiver_node:
  ros__parameters:
    slam_mode: false
    map_frame: map
    lidar_frame: velodyne_top
    gnss_frame: gnss_link
    imu_frame: imu

morai_traffic_light_sender_node:
  ros__parameters:
    simulator_ip: "192.168.0.27"
    traffic_light_udp_port: 4000
    input_topic: "/SetTrafficLight"

traffic_light_map_ui:
  ros__parameters:
    map_path: "/home/sws/autoware_map/K_city/K_city_26.osm"
    host: "127.0.0.1"
    port: 18080
    output_topic: "/SetTrafficLight"
