waypoint_follower_base:
  ros__parameters:
    # Waypoint file path
    waypoint_file_path: "/home/ljh/workspace/CMC-AI_2026/src/ad_src/src/waypoint_recorder/waypoints.csv"

    # Control parameters
    lookahead_distance: 12.0 #10.0 #5.0 #2.0 #4.0 #2.5  # [m] Pure pursuit lookahead distance
    state_update_rate: 50.0  # [Hz] Rate for state estimation updates
    mpc_prediction_horizon: 20  # MUST match MPC prediction_horizon parameter!

    # Topic names
    odom_topic: "/Ego/odom"

    # Frame IDs
    frame_id: "odom"

    # Waypoint randomization (for dataset diversity)
    randomize_waypoints: true
    randomize_lateral_offset_max: 1.0   # [m] left/right max offset
    randomize_speed_min: 8.0            # [m/s]
    randomize_speed_max: 11.0           # [m/s]
    randomize_smoothing_window: 8       # odd >=1, 1 = no smoothing
    randomize_seed: 0                   # 0 = random_device
    randomize_recompute_yaw: true
